// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjmCet6Pivnl28YxQHARVd6zBCfGpez0c',
    appId: '1:343433390663:web:6a9c6e3932614198509f62',
    messagingSenderId: '343433390663',
    projectId: 'todo-356be',
    authDomain: 'todo-356be.firebaseapp.com',
    storageBucket: 'todo-356be.firebasestorage.app',
    measurementId: 'G-1N5WYJKCNX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH6GK7OW2r4L7DzL6JfTg75K-zQBKMlyI',
    appId: '1:343433390663:android:b6d90f5f995c3d83509f62',
    messagingSenderId: '343433390663',
    projectId: 'todo-356be',
    storageBucket: 'todo-356be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0B_3IhsXFlNzrcUsIDHdIXT9SAQDP-y0',
    appId: '1:343433390663:ios:a3e43355f3a5e0f4509f62',
    messagingSenderId: '343433390663',
    projectId: 'todo-356be',
    storageBucket: 'todo-356be.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0B_3IhsXFlNzrcUsIDHdIXT9SAQDP-y0',
    appId: '1:343433390663:ios:a3e43355f3a5e0f4509f62',
    messagingSenderId: '343433390663',
    projectId: 'todo-356be',
    storageBucket: 'todo-356be.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjmCet6Pivnl28YxQHARVd6zBCfGpez0c',
    appId: '1:343433390663:web:9c7aa7ab22914c6c509f62',
    messagingSenderId: '343433390663',
    projectId: 'todo-356be',
    authDomain: 'todo-356be.firebaseapp.com',
    storageBucket: 'todo-356be.firebasestorage.app',
    measurementId: 'G-SRN8451GBL',
  );
}
